name: e2e tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
          start: npm start
          wait-on: http://localhost:3000
